_SAMPLES = [
    {
        "risk_score": 82,
        "summary": "여러 보안 헤더가 누락되어 있고 민감한 경로가 외부에 노출되어 있습니다. 즉각적인 조치가 필요합니다.",
        "ssl": {"valid": True, "issuer": "Let's Encrypt", "expires_in_days": 45, "protocol": "TLSv1.2"},
        "server_info": {"server": "Apache/2.4.29", "x_powered_by": "PHP/7.2.0"},
        "findings": [
            {"id": "WEB-001", "severity": "HIGH", "category": "보안 헤더",
             "title": "HSTS(HTTP Strict Transport Security) 누락",
             "description": "HSTS 헤더가 없어 SSL 스트립 공격에 취약합니다.",
             "recommendation": "Strict-Transport-Security: max-age=31536000; includeSubDomains 추가"},
            {"id": "WEB-002", "severity": "HIGH", "category": "보안 헤더",
             "title": "Content-Security-Policy(CSP) 누락",
             "description": "CSP 헤더가 없어 XSS 공격에 노출될 수 있습니다.",
             "recommendation": "Content-Security-Policy 헤더를 설정해 허용 리소스를 제한하세요."},
            {"id": "WEB-003", "severity": "CRITICAL", "category": "경로 노출",
             "title": "/.env 파일 외부 접근 가능",
             "description": "환경변수 파일이 공개 접근 가능합니다. DB 비밀번호·API 키가 노출될 수 있습니다.",
             "recommendation": "웹 서버 설정에서 .env 파일 접근을 차단하세요."},
            {"id": "WEB-004", "severity": "HIGH", "category": "서버 정보",
             "title": "서버 버전 정보 노출",
             "description": "Server 헤더에 Apache 버전이 노출되어 알려진 취약점 공격에 악용될 수 있습니다.",
             "recommendation": "ServerTokens Prod 설정으로 버전 정보를 숨기세요."},
            {"id": "WEB-005", "severity": "MEDIUM", "category": "보안 헤더",
             "title": "X-Frame-Options 누락",
             "description": "클릭재킹(Clickjacking) 공격에 취약합니다.",
             "recommendation": "X-Frame-Options: SAMEORIGIN 또는 DENY 추가"},
            {"id": "WEB-006", "severity": "MEDIUM", "category": "보안 헤더",
             "title": "X-Content-Type-Options 누락",
             "description": "브라우저 MIME 타입 스니핑으로 인한 공격에 취약합니다.",
             "recommendation": "X-Content-Type-Options: nosniff 추가"},
            {"id": "WEB-007", "severity": "LOW", "category": "경로 노출",
             "title": "/robots.txt 접근 가능",
             "description": "내부 경로 구조가 노출될 수 있습니다.",
             "recommendation": "민감한 내부 경로를 robots.txt에서 제거하세요."},
        ],
        "exposed_paths": ["/.env", "/robots.txt"],
        "_mock": True,
    },
    {
        "risk_score": 48,
        "summary": "일부 보안 헤더가 누락되어 있습니다. 권장 설정을 적용하면 보안 수준을 높일 수 있습니다.",
        "ssl": {"valid": True, "issuer": "DigiCert", "expires_in_days": 180, "protocol": "TLSv1.3"},
        "server_info": {"server": "nginx", "x_powered_by": None},
        "findings": [
            {"id": "WEB-001", "severity": "MEDIUM", "category": "보안 헤더",
             "title": "Content-Security-Policy(CSP) 미설정",
             "description": "CSP 헤더가 없어 XSS 공격에 노출될 수 있습니다.",
             "recommendation": "Content-Security-Policy 헤더를 설정해 허용 리소스를 제한하세요."},
            {"id": "WEB-002", "severity": "MEDIUM", "category": "보안 헤더",
             "title": "Referrer-Policy 누락",
             "description": "페이지 이동 시 내부 URL이 외부로 유출될 수 있습니다.",
             "recommendation": "Referrer-Policy: strict-origin-when-cross-origin 추가"},
            {"id": "WEB-003", "severity": "LOW", "category": "보안 헤더",
             "title": "Permissions-Policy 미설정",
             "description": "카메라·마이크 등 브라우저 기능 접근 제한이 없습니다.",
             "recommendation": "Permissions-Policy 헤더로 불필요한 브라우저 기능을 비활성화하세요."},
            {"id": "WEB-004", "severity": "LOW", "category": "경로 노출",
             "title": "/robots.txt 접근 가능",
             "description": "내부 경로 구조가 노출될 수 있습니다.",
             "recommendation": "민감한 경로를 robots.txt에서 제거하세요."},
        ],
        "exposed_paths": ["/robots.txt"],
        "_mock": True,
    },
    {
        "risk_score": 15,
        "summary": "전반적으로 보안 설정이 양호합니다. 소수의 개선 사항만 존재합니다.",
        "ssl": {"valid": True, "issuer": "DigiCert EV", "expires_in_days": 280, "protocol": "TLSv1.3"},
        "server_info": {"server": None, "x_powered_by": None},
        "findings": [
            {"id": "WEB-001", "severity": "LOW", "category": "보안 헤더",
             "title": "Permissions-Policy 미설정",
             "description": "브라우저 기능 접근 제한 헤더가 없습니다.",
             "recommendation": "Permissions-Policy 헤더로 불필요한 기능을 비활성화하세요."},
        ],
        "exposed_paths": [],
        "_mock": True,
    },
    {
        "risk_score": 67,
        "summary": "SSL 설정이 취약하고 여러 보안 헤더가 누락되어 있습니다.",
        "ssl": {"valid": True, "issuer": "Self-signed", "expires_in_days": 12, "protocol": "TLSv1.1"},
        "server_info": {"server": "Microsoft-IIS/8.5", "x_powered_by": "ASP.NET"},
        "findings": [
            {"id": "WEB-001", "severity": "HIGH", "category": "SSL/TLS",
             "title": "만료 임박한 SSL 인증서 (12일 후 만료)",
             "description": "인증서가 12일 후 만료됩니다. 갱신하지 않으면 서비스가 차단됩니다.",
             "recommendation": "즉시 SSL 인증서를 갱신하세요."},
            {"id": "WEB-002", "severity": "HIGH", "category": "SSL/TLS",
             "title": "구형 TLS 버전 사용 (TLSv1.1)",
             "description": "TLSv1.1은 알려진 취약점이 있습니다. TLSv1.2 이상을 사용하세요.",
             "recommendation": "서버에서 TLSv1.2, TLSv1.3만 허용하도록 설정하세요."},
            {"id": "WEB-003", "severity": "HIGH", "category": "서버 정보",
             "title": "IIS 및 ASP.NET 버전 정보 노출",
             "description": "서버 기술 스택이 노출되어 알려진 취약점 공격에 악용될 수 있습니다.",
             "recommendation": "IIS에서 Server 헤더 제거 및 X-Powered-By 헤더를 삭제하세요."},
            {"id": "WEB-004", "severity": "MEDIUM", "category": "보안 헤더",
             "title": "HSTS 누락",
             "description": "HTTPS 강제 적용 헤더가 없습니다.",
             "recommendation": "Strict-Transport-Security 헤더를 추가하세요."},
        ],
        "exposed_paths": [],
        "_mock": True,
    },
]


def generate_mock_webscan(url: str) -> dict:
    idx = len(url) % len(_SAMPLES)
    sample = _SAMPLES[idx]
    counts = {"CRITICAL": 0, "HIGH": 0, "MEDIUM": 0, "LOW": 0}
    for f in sample["findings"]:
        s = f["severity"]
        if s in counts:
            counts[s] += 1
    return {"url": url, **sample, "counts": counts}
